# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/mylifeforrent"
  zhihu: "https://www.zhihu.com/people/temple-80/activities"
  mail: "Mailto:13597794022@163.com"
  #qq: "1299351443"
  weibo: "http://weibo.com/3194670253/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1"
  # rss: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
# excerpt_link: 阅读全文
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# 百度统计、谷歌统计
baidu_tongji: true
google_analytics: true

favicon: http://pics.sc.chinaz.com/files/pic/pic9/201511/apic16077.jpg

#你的头像url
avatar: http://pics.sc.chinaz.com/files/pic/pic9/201511/apic16077.jpg

#是否开启分享
share: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: your duoshuo id

#是否开启云标签
tagcloud: true

#是否开启文章阅读量
leancloud_visitors:
  enable: true
  app_id: 6QxuusVrKHwm2mV3yiIMs8tG-gzGzoHsz
  app_key: tIMOfNCJYN6EOXphMqaFtUIN


#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  smackdown: https://github.com/smackgg/hexo-theme-smackdown
#是否开启“关于我”。
# 不开启——
aboutme: false
#开启——
# aboutme:

swift_search:
  enable: true
